// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy5WHX6SMMWDFtjZRVwv9E_AWC2uwEPYE',
    appId: '1:136569334195:web:00f4550e52ac29e32b03c6',
    messagingSenderId: '136569334195',
    projectId: 'icmr-backend',
    authDomain: 'icmr-backend.firebaseapp.com',
    storageBucket: 'icmr-backend.appspot.com',
    measurementId: 'G-SGWD85RX9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOCZCiwPCQbXPsoLqBY1TmeSVQvJIQS9Y',
    appId: '1:136569334195:android:258139078ba4343e2b03c6',
    messagingSenderId: '136569334195',
    projectId: 'icmr-backend',
    storageBucket: 'icmr-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5eb3pMQb7vFVEkEHq046RAOQUxTVFRNI',
    appId: '1:136569334195:ios:099b42d0a87675e52b03c6',
    messagingSenderId: '136569334195',
    projectId: 'icmr-backend',
    storageBucket: 'icmr-backend.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5eb3pMQb7vFVEkEHq046RAOQUxTVFRNI',
    appId: '1:136569334195:ios:099b42d0a87675e52b03c6',
    messagingSenderId: '136569334195',
    projectId: 'icmr-backend',
    storageBucket: 'icmr-backend.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
